name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: linuxuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/food-park

            # Reset quyền nếu cần
            sudo chown -R linuxuser:www-data .
            sudo chmod -R 775 storage bootstrap/cache

            # Pull code mới
            git stash            # Lưu thay đổi tạm thời
            git pull origin main # Kéo code mới về
            git stash pop

            # Cài đặt dependencies
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build

            # Migrate database nếu cần
            php artisan migrate --force

            # Reset quyền sau deploy
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # Restart web server
            sudo systemctl restart php8.1-fpm
            sudo systemctl restart nginx
